import type { Question } from "../../types";
import { DIEM_LIET_IDS } from "../../types";

// Bộ câu hỏi mẫu đại diện cho cấu trúc 600 câu BCA (hiệu lực 01/06/2025)
// Full 600-câu JSON sẽ được load từ file riêng khi có bản quyền nội dung
// Cấu trúc: ID 1-180 (Chương I), 181-205 (II), 206-263 (III), 264-300 (IV), 301-485 (V), 486-600 (VI)

export const SAMPLE_QUESTIONS: Question[] = [
  // ===== CHƯƠNG I: Quy tắc giao thông (câu 1-180) =====
  {
    id: 1,
    chapter: 1,
    content: "Người điều khiển xe cơ giới phải đi bên nào của đường?",
    options: ["Đi bên trái", "Đi bên phải theo chiều đi của mình", "Đi giữa đường", "Tùy ý chọn làn"],
    answer: 1,
    explanation: "Theo Luật Trật tự ATGT đường bộ 2024, người điều khiển xe cơ giới phải đi bên phải theo chiều đi của mình, trong phần đường dành cho xe cơ giới.",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 19,
    chapter: 1,
    content: "Hành vi nào sau đây bị nghiêm cấm khi tham gia giao thông đường bộ?",
    options: [
      "Đi đúng phần đường, làn đường",
      "Điều khiển xe khi trong máu hoặc hơi thở có nồng độ cồn",
      "Nhường đường cho xe ưu tiên",
      "Dừng xe đúng nơi quy định",
    ],
    answer: 1,
    explanation: "Điều khiển xe khi có nồng độ cồn trong máu hoặc hơi thở là hành vi bị nghiêm cấm tuyệt đối. Đây là câu ĐIỂM LIỆT — trả lời sai là trượt toàn bài.",
    isDiemLiet: true,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 20,
    chapter: 1,
    content: "Người điều khiển xe ô tô có nồng độ cồn trong máu vượt quá bao nhiêu mg/100ml máu bị cấm lái xe?",
    options: ["50 mg/100ml", "80 mg/100ml", "0 mg/100ml (không được có)", "100 mg/100ml"],
    answer: 2,
    explanation: "Theo Luật TTATGT 2024, người điều khiển ô tô tuyệt đối không được có nồng độ cồn trong máu (0 mg/100ml). Câu ĐIỂM LIỆT.",
    isDiemLiet: true,
    licenseClasses: ["B", "B1", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 21,
    chapter: 1,
    content: "Hành vi nào sau đây bị coi là vi phạm nghiêm trọng có thể dẫn đến trượt thi lý thuyết ngay lập tức?",
    options: [
      "Vượt đèn xanh",
      "Vượt đèn đỏ",
      "Dừng trước vạch dừng",
      "Bật đèn xi nhan khi chuyển làn",
    ],
    answer: 1,
    explanation: "Vượt đèn đỏ là hành vi vi phạm nghiêm trọng, thuộc nhóm câu ĐIỂM LIỆT trong bộ đề BCA 2025.",
    isDiemLiet: true,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 47,
    chapter: 1,
    content: "Khi gặp xe cảnh sát, xe cứu thương, xe cứu hỏa đang hú còi ưu tiên, người lái xe phải làm gì?",
    options: [
      "Tiếp tục đi bình thường",
      "Tăng tốc để tránh xa",
      "Nhường đường, kể cả phải dừng lại hoặc đi vào lề",
      "Bấm còi để báo hiệu",
    ],
    answer: 2,
    explanation: "Phải nhường đường cho xe ưu tiên kể cả khi đang có đèn xanh. Không nhường là vi phạm nghiêm trọng — câu ĐIỂM LIỆT.",
    isDiemLiet: true,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 63,
    chapter: 1,
    content: "Người điều khiển xe mô tô, xe gắn máy được phép chạy quá tốc độ tối đa trong trường hợp nào?",
    options: [
      "Khi đường vắng không có người đi bộ",
      "Khi khẩn cấp cần đến bệnh viện",
      "Không được phép trong bất kỳ trường hợp nào",
      "Khi vượt xe khác trên đường cao tốc",
    ],
    answer: 2,
    explanation: "Không được vượt tốc độ tối đa trong bất kỳ trường hợp nào. Câu ĐIỂM LIỆT.",
    isDiemLiet: true,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 85,
    chapter: 1,
    content: "Người lái xe sử dụng điện thoại di động khi đang lái xe (trừ thiết bị hỗ trợ tay không) là hành vi:",
    options: [
      "Được phép nếu dừng đèn đỏ",
      "Bị nghiêm cấm",
      "Được phép trong đô thị",
      "Được phép nếu tốc độ thấp",
    ],
    answer: 1,
    explanation: "Sử dụng điện thoại cầm tay khi đang lái xe bị nghiêm cấm theo Luật TTATGT 2024. Câu ĐIỂM LIỆT.",
    isDiemLiet: true,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 97,
    chapter: 1,
    content: "Tốc độ tối đa của xe ô tô con khi đi trên đường cao tốc là bao nhiêu km/h?",
    options: ["100 km/h", "110 km/h", "120 km/h", "130 km/h"],
    answer: 2,
    explanation: "Xe ô tô con trên đường cao tốc tối đa 120 km/h theo quy định hiện hành. Câu ĐIỂM LIỆT nếu liên quan đến vi phạm tốc độ.",
    isDiemLiet: true,
    licenseClasses: ["B", "B1", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 5,
    chapter: 1,
    content: "Khi gặp đường giao nhau không có biển báo và đèn tín hiệu, xe nào được ưu tiên đi trước?",
    options: [
      "Xe đi từ trái sang phải",
      "Xe đi từ phải sang trái",
      "Xe đi thẳng",
      "Xe từ đường nhỏ ra đường lớn",
    ],
    answer: 1,
    explanation: "Tại ngã tư không có tín hiệu, xe bên phải được ưu tiên (nhường đường cho xe từ bên phải đến).",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 10,
    chapter: 1,
    content: "Khoảng cách an toàn tối thiểu giữa hai xe khi đi trên đường với tốc độ 60 km/h là bao nhiêu mét?",
    options: ["20 m", "35 m", "50 m", "60 m"],
    answer: 1,
    explanation: "Theo quy định, khi đi 60 km/h khoảng cách an toàn tối thiểu là 35 m (= tốc độ/2 + 5).",
    isDiemLiet: false,
    licenseClasses: ["B", "B1", "C1", "C", "D1", "D2", "D"],
  },

  // ===== CHƯƠNG II: Văn hóa giao thông & Đạo đức (câu 181-205) =====
  {
    id: 181,
    chapter: 2,
    content: "Hành vi nào thể hiện văn hóa giao thông tốt?",
    options: [
      "Bấm còi liên tục khi bị tắc đường",
      "Nhường đường cho người đi bộ qua đường",
      "Vượt đèn đỏ khi vội",
      "Đỗ xe trên vạch sang đường",
    ],
    answer: 1,
    explanation: "Nhường đường cho người đi bộ là hành vi văn hóa giao thông cơ bản.",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 197,
    chapter: 2,
    content: "Khi phát hiện người bị tai nạn giao thông, người lái xe có trách nhiệm gì?",
    options: [
      "Tiếp tục đi để tránh ùn tắc",
      "Dừng xe, sơ cứu nạn nhân và báo cơ quan chức năng",
      "Quay phim rồi đăng mạng xã hội",
      "Chờ người khác đến xử lý",
    ],
    answer: 1,
    explanation: "Người lái xe có trách nhiệm pháp lý phải dừng lại, sơ cứu và báo cáo. Bỏ qua nạn nhân là vi phạm pháp luật. Câu ĐIỂM LIỆT.",
    isDiemLiet: true,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 198,
    chapter: 2,
    content: "Theo quy định mới, bình chữa cháy trên xe ô tô là:",
    options: [
      "Trang bị tùy chọn, không bắt buộc",
      "Bắt buộc phải có và còn hạn sử dụng",
      "Chỉ bắt buộc với xe tải",
      "Chỉ bắt buộc với xe từ 7 chỗ trở lên",
    ],
    answer: 1,
    explanation: "Bình chữa cháy là thiết bị bắt buộc trên xe ô tô và phải còn hạn sử dụng. Câu ĐIỂM LIỆT.",
    isDiemLiet: true,
    licenseClasses: ["B", "B1", "C1", "C", "D1", "D2", "D"],
  },

  // ===== CHƯƠNG III: Kỹ thuật lái xe (câu 206-263) =====
  {
    id: 206,
    chapter: 3,
    content: "Khi phanh khẩn cấp trên đường ướt, người lái xe nên:",
    options: [
      "Đạp phanh thật mạnh một lần",
      "Đánh lái sang bên",
      "Đạp phanh từ từ, tránh khóa bánh",
      "Tăng ga để giữ thăng bằng",
    ],
    answer: 2,
    explanation: "Trên đường ướt, khóa bánh xe gây mất lái. Cần phanh nhẹ, nhấp nhả để duy trì kiểm soát. Câu ĐIỂM LIỆT.",
    isDiemLiet: true,
    licenseClasses: ["B", "B1", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 220,
    chapter: 3,
    content: "Khi lái xe xuống dốc dài, cách xử lý đúng là:",
    options: [
      "Về số N để tiết kiệm xăng",
      "Giữ số thấp, sử dụng phanh động cơ kết hợp phanh chân",
      "Đạp phanh liên tục từ trên xuống",
      "Tắt máy để tiết kiệm nhiên liệu",
    ],
    answer: 1,
    explanation: "Xuống dốc dài phải dùng phanh động cơ (số thấp) kết hợp phanh chân từng đợt, tránh cháy phanh.",
    isDiemLiet: false,
    licenseClasses: ["B", "B1", "C1", "C", "D1", "D2", "D"],
  },

  // ===== CHƯƠNG IV: Cấu tạo xe (câu 264-300) =====
  {
    id: 264,
    chapter: 4,
    content: "Đèn báo nhiệt độ nước làm mát sáng đỏ khi đang lái xe, người lái phải làm gì?",
    options: [
      "Tiếp tục đi bình thường",
      "Tăng tốc để làm mát máy",
      "Dừng xe ngay, tắt máy và kiểm tra",
      "Đổ thêm xăng",
    ],
    answer: 2,
    explanation: "Đèn nhiệt độ đỏ cảnh báo động cơ đang quá nóng. Phải dừng ngay để tránh hỏng máy.",
    isDiemLiet: false,
    licenseClasses: ["B", "B1", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 280,
    chapter: 4,
    content: "Hệ thống ABS (Anti-lock Braking System) có tác dụng gì?",
    options: [
      "Tăng tốc độ phanh",
      "Ngăn bánh xe bị khóa cứng khi phanh gấp, giúp giữ lái",
      "Giảm tiêu hao nhiên liệu",
      "Tăng lực kéo lên dốc",
    ],
    answer: 1,
    explanation: "ABS ngăn bánh bị khóa khi phanh gấp, cho phép tài xế vẫn điều khiển hướng được trong khi phanh.",
    isDiemLiet: false,
    licenseClasses: ["B", "C1", "C", "D1", "D2", "D"],
  },

  // ===== CHƯƠNG V: Biển báo đường bộ (câu 301-485) =====
  {
    id: 301,
    chapter: 5,
    content: "Biển báo hình tròn viền đỏ, nền trắng có ý nghĩa gì?",
    options: [
      "Biển báo nguy hiểm",
      "Biển cấm — cấm thực hiện hành vi được mô tả",
      "Biển hiệu lệnh bắt buộc",
      "Biển chỉ dẫn thông tin",
    ],
    answer: 1,
    explanation: "Biển tròn viền đỏ nền trắng là biển CẤM. Ví dụ: biển cấm quay đầu, cấm vượt...",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 320,
    chapter: 5,
    content: "Biển báo hình tam giác viền đỏ cảnh báo điều gì?",
    options: [
      "Cấm xe tải",
      "Nguy hiểm hoặc cảnh báo — cần chú ý phía trước",
      "Đường ưu tiên",
      "Bắt buộc đi thẳng",
    ],
    answer: 1,
    explanation: "Biển tam giác viền đỏ là biển NGUY HIỂM, cảnh báo người lái về tình huống nguy hiểm phía trước.",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 350,
    chapter: 5,
    content: "Biển báo hình tròn nền xanh lam có ý nghĩa gì?",
    options: [
      "Biển cấm",
      "Biển nguy hiểm",
      "Biển hiệu lệnh — bắt buộc thực hiện",
      "Biển chỉ dẫn",
    ],
    answer: 2,
    explanation: "Biển tròn nền xanh lam là biển HIỆU LỆNH — bắt buộc phải tuân theo. Ví dụ: phải đi thẳng, phải rẽ phải...",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 400,
    chapter: 5,
    content: "Biển P (đỗ xe) hình vuông nền xanh lam có nghĩa là:",
    options: [
      "Cấm đỗ xe",
      "Được phép đỗ xe tại khu vực này",
      "Đỗ xe có thu phí",
      "Đỗ xe 30 phút",
    ],
    answer: 1,
    explanation: "Biển P nền xanh chỉ dẫn nơi được phép đỗ xe.",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },

  // ===== CHƯƠNG VI: Tình huống & Sa hình (câu 486-600) =====
  {
    id: 486,
    chapter: 6,
    content: "Xe A đang đi thẳng, xe B từ đường nhánh đâm ra bên phải xe A. Ai phải nhường đường?",
    options: [
      "Xe A nhường xe B vì xe B ở bên phải",
      "Xe B nhường xe A vì xe A đang đi trên đường chính",
      "Xe nào đến trước đi trước",
      "Xe nhỏ hơn nhường xe lớn hơn",
    ],
    answer: 1,
    explanation: "Xe đi từ đường nhánh ra phải nhường xe đang đi trên đường chính (có quyền ưu tiên cao hơn).",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 245,
    chapter: 3,
    content: "Khi lái xe trên đường, phát hiện lốp xe bị xẹp đột ngột, cần xử lý thế nào?",
    options: [
      "Đạp phanh mạnh ngay lập tức",
      "Giữ vô lăng thẳng, thả ga từ từ, phanh nhẹ và dừng xe vào lề",
      "Đánh lái mạnh sang một bên",
      "Tăng ga để giữ thăng bằng",
    ],
    answer: 1,
    explanation: "Khi nổ lốp: giữ vô lăng thẳng, không phanh gấp (xe mất lái), thả ga từ từ rồi phanh nhẹ vào lề. Câu ĐIỂM LIỆT.",
    isDiemLiet: true,
    licenseClasses: ["B", "B1", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 246,
    chapter: 3,
    content: "Khi xe bị mất phanh khi đang xuống dốc, cách xử lý đúng nhất là:",
    options: [
      "Tắt máy xe",
      "Đánh lái sang bên đường để chạy song song rồi dùng phanh tay, tìm chỗ chặn xe",
      "Nhảy ra khỏi xe ngay",
      "Bấm còi liên tục và tiếp tục chạy",
    ],
    answer: 1,
    explanation: "Mất phanh: dùng phanh tay từng đợt, về số thấp, tìm lề đường, chướng ngại vật mềm để giảm tốc. Câu ĐIỂM LIỆT.",
    isDiemLiet: true,
    licenseClasses: ["B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 500,
    chapter: 6,
    content: "Tại ngã tư có đèn tín hiệu, đèn xanh bật, nhưng phía trước có xe cứu thương đang hú còi. Bạn phải:",
    options: [
      "Đi thẳng vì đèn đang xanh",
      "Dừng lại hoặc tránh sang bên để nhường xe cứu thương",
      "Bấm còi để xe cứu thương tránh bạn",
      "Vượt nhanh để thoát khỏi ngã tư",
    ],
    answer: 1,
    explanation: "Xe ưu tiên (cứu thương) được ưu tiên tuyệt đối, kể cả khi đèn xanh. Phải nhường đường.",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 550,
    chapter: 6,
    content: "Khi gặp đường sắt có đèn đỏ nhấp nháy, người lái xe phải:",
    options: [
      "Đi nhanh qua trước khi tàu đến",
      "Dừng hẳn trước vạch dừng, chờ đèn tắt và đường thông thoáng",
      "Nhìn trái phải rồi đi qua",
      "Đi chậm qua đường sắt",
    ],
    answer: 1,
    explanation: "Đèn đỏ nhấp nháy tại đường sắt: PHẢI dừng lại hoàn toàn trước vạch. Câu ĐIỂM LIỆT.",
    isDiemLiet: true,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },

  // ===== CHƯƠNG VII: Luật hình sự & Xử phạt hành chính (MỚI từ 1/7/2026) =====
  {
    id: 601,
    chapter: 7,
    content: "Theo Bộ Luật Hình sự 2015 (sửa đổi), người điều khiển xe vi phạm nồng độ cồn gây tai nạn chết người có thể bị phạt tù tối đa bao nhiêu năm?",
    options: ["3 năm", "5 năm", "10 năm", "15 năm"],
    answer: 3,
    explanation: "Điều 260 BLHS 2015: Vi phạm quy định về tham gia giao thông đường bộ gây chết người khi có nồng độ cồn có thể bị phạt tù đến 15 năm (khoản 3 — trường hợp đặc biệt nghiêm trọng).",
    type: "mcq" as const,
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"] as any,
  },
  {
    id: 602,
    chapter: 7,
    content: "Hành vi bỏ trốn sau khi gây tai nạn giao thông có bị truy cứu trách nhiệm hình sự không?",
    options: ["Có — là tình tiết tăng nặng, có thể bị truy cứu thêm tội bỏ mặc người bị nạn", "Không — chỉ bị xử phạt hành chính", "Chỉ bị phạt tiền", "Không bị xử lý nếu không có camera"],
    answer: 0,
    explanation: "Theo BLHS 2015, bỏ trốn sau tai nạn là tình tiết tăng nặng định khung. Người bỏ mặc nạn nhân có thể bị xử lý thêm về tội 'không cứu giúp người đang trong tình trạng nguy hiểm đến tính mạng' (Điều 132).",
    type: "mcq" as const,
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"] as any,
  },
  {
    id: 603,
    chapter: 7,
    content: "Theo Nghị định 168/2024/NĐ-CP, mức phạt tiền cao nhất đối với xe ô tô vượt đèn đỏ là bao nhiêu?",
    options: ["4-6 triệu đồng", "6-8 triệu đồng", "18-20 triệu đồng", "20-22 triệu đồng"],
    answer: 2,
    explanation: "Nghị định 168/2024 tăng mạnh mức phạt: Ô tô vượt đèn đỏ bị phạt 18-20 triệu đồng + tước GPLX 6-8 tháng. Mức này gấp nhiều lần so với quy định cũ (1.2-2 triệu).",
    type: "mcq" as const,
    isDiemLiet: false,
    licenseClasses: ["B", "B1", "C1", "C", "D1", "D2", "D"] as any,
  },
  {
    id: 604,
    chapter: 7,
    content: "Đúng hay Sai: Theo hệ thống trừ điểm GPLX mới (từ 1/1/2025), mỗi GPLX có 12 điểm mỗi năm — khi hết điểm thì bằng lái bị đình chỉ hiệu lực.",
    options: ["Đúng", "Sai", "Đúng — nhưng chỉ áp dụng cho ô tô, không áp dụng cho xe máy", "Sai — có 20 điểm mỗi năm"],
    answer: 0,
    explanation: "ĐÚNG. Luật TTATGT 2024 quy định mỗi GPLX có 12 điểm/năm. Vi phạm bị trừ điểm tương ứng. Hết 12 điểm → GPLX bị đình chỉ hiệu lực, phải thi lại lý thuyết để phục hồi.",
    type: "truefalse" as const,
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"] as any,
  },
  {
    id: 605,
    chapter: 7,
    content: "Đúng hay Sai: Vượt tốc độ trên 35 km/h so với quy định bị trừ 6 điểm GPLX và có thể bị tước bằng lái.",
    options: ["Đúng", "Sai — chỉ trừ 2 điểm", "Sai — không áp dụng trừ điểm cho lỗi tốc độ", "Đúng — nhưng chỉ trên cao tốc"],
    answer: 0,
    explanation: "ĐÚNG. Theo Nghị định 168/2024 và bảng trừ điểm GPLX: Vượt tốc độ >35 km/h bị trừ 6 điểm + phạt tiền cao + có thể tước GPLX 2-4 tháng.",
    type: "truefalse" as const,
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"] as any,
  },
  {
    id: 606,
    chapter: 7,
    content: "Người điều khiển xe mô tô có nồng độ cồn trong hơi thở từ 0,25 mg/l đến dưới 0,4 mg/l bị xử phạt như thế nào?",
    options: [
      "Phạt cảnh cáo",
      "Phạt tiền 4-5 triệu, tước GPLX 10-12 tháng",
      "Phạt tiền 6-8 triệu, tước GPLX 22-24 tháng",
      "Tịch thu phương tiện",
    ],
    answer: 1,
    explanation: "Theo Nghị định 168/2024: Xe máy có nồng độ cồn mức 2 (0,25-dưới 0,4 mg/l hơi thở) bị phạt 4-5 triệu đồng và tước GPLX 10-12 tháng.",
    type: "mcq" as const,
    isDiemLiet: false,
    licenseClasses: ["A1", "A"] as any,
  },
  {
    id: 607,
    chapter: 7,
    content: "Theo quy định đào tạo mới (Thông tư 17/2026), học viên hạng B bắt buộc học thêm nội dung nào so với trước?",
    options: [
      "Lái xe ban đêm",
      "Phòng cháy chữa cháy (PCCC) và kỹ năng cứu hộ cứu nạn — 4 giờ bắt buộc",
      "Lái xe trên đường cao tốc",
      "Lái xe tải nhẹ",
    ],
    answer: 1,
    explanation: "Thông tư 17/2026/TT-BXD (hiệu lực 1/7/2026): Học viên hạng B và C1 phải học 4 giờ PCCC và cứu hộ cứu nạn, thêm 4 giờ phần mềm mô phỏng tình huống và 2 giờ cabin lái xe mô phỏng.",
    type: "mcq" as const,
    isDiemLiet: false,
    licenseClasses: ["B", "B1", "C1"] as any,
  },

  // ===== CHƯƠNG I — bổ sung thêm (câu 11-18, 29, 31, 33...) =====
  {
    id: 11,
    chapter: 1,
    content: "Khi muốn chuyển hướng xe, người lái phải bật đèn xi nhan trước khi thực hiện ít nhất bao lâu?",
    options: ["Bật đồng thời khi chuyển hướng", "Ít nhất 30 mét trước khi chuyển hướng", "Ít nhất 50 mét trước khi chuyển hướng", "Khi đã vào cua"],
    answer: 0,
    explanation: "Người lái phải bật đèn tín hiệu xin đường (xi nhan) TRƯỚC khi thực hiện động tác chuyển hướng, đủ để xe sau có thể phản ứng. Tuy nhiên quy định không đặt ngưỡng khoảng cách cố định — quan trọng là bật trước để báo hiệu.",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 12,
    chapter: 1,
    content: "Xe nào được ưu tiên đi trước tại ngã tư khi đèn tín hiệu hỏng?",
    options: ["Xe to hơn", "Xe từ đường lớn hơn", "Xe bên phải", "Xe đến trước"],
    answer: 2,
    explanation: "Khi đèn hỏng, áp dụng quy tắc đường không ưu tiên: nhường đường cho xe đến từ bên phải. Đây là quy tắc 'ưu tiên bên phải'.",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 13,
    chapter: 1,
    content: "Người điều khiển xe mô tô có được phép chở 2 người lớn không?",
    options: ["Được phép nếu đường vắng", "Không được phép — chỉ chở tối đa 1 người lớn + 1 trẻ em dưới 14 tuổi", "Được nếu có giấy phép hạng A", "Được nếu xe có tải trọng lớn"],
    answer: 1,
    explanation: "Xe mô tô chỉ được chở tối đa 1 người lớn (hoặc 1 người lớn + 1 trẻ em dưới 14 tuổi ngồi trước người lái). Chở 2 người lớn là vi phạm.",
    isDiemLiet: false,
    licenseClasses: ["A1", "A"],
  },
  {
    id: 14,
    chapter: 1,
    content: "Trên đường có vạch liền kẻ giữa, xe có được phép vượt không?",
    options: ["Được nếu không có xe ngược chiều", "Không được phép vượt qua vạch liền", "Được nếu đường thẳng và nhìn thấy xa", "Được nếu đi chậm"],
    answer: 1,
    explanation: "Vạch liền (liên tục) nghĩa là KHÔNG được phép vượt qua. Chỉ được vượt khi có vạch đứt (gián đoạn).",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 15,
    chapter: 1,
    content: "Tốc độ tối đa cho phép trong khu dân cư (đường đôi có dải phân cách) là bao nhiêu km/h?",
    options: ["40 km/h", "50 km/h", "60 km/h", "70 km/h"],
    answer: 2,
    explanation: "Trong khu dân cư trên đường đôi có dải phân cách, tốc độ tối đa là 60 km/h. Đường đơn trong khu dân cư là 50 km/h.",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 16,
    chapter: 1,
    content: "Khi đèn vàng bật sáng (không nhấp nháy), người lái xe phải làm gì?",
    options: ["Tăng tốc để qua trước khi đèn đỏ", "Dừng lại trước vạch dừng nếu có thể dừng an toàn", "Tiếp tục đi bình thường", "Giảm tốc và chú ý"],
    answer: 1,
    explanation: "Đèn vàng không nhấp nháy: cảnh báo sắp chuyển sang đỏ, phải dừng trước vạch nếu dừng an toàn. Không được tăng tốc để lách qua.",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 17,
    chapter: 1,
    content: "Xe ô tô được phép đi trên làn đường dành riêng cho xe buýt khi nào?",
    options: ["Khi không có xe buýt", "Khi cần rẽ trong khoảng 50m gần nút giao", "Không được phép trong bất kỳ trường hợp nào", "Khi đường đông"],
    answer: 1,
    explanation: "Theo quy định, xe ô tô không được đi vào làn xe buýt, trừ khi cần rẽ trong phạm vi gần nút giao (thường là 50m) và có tín hiệu xi nhan.",
    isDiemLiet: false,
    licenseClasses: ["B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 18,
    chapter: 1,
    content: "Khoảng cách tối thiểu khi dừng, đỗ xe so với miệng cống thoát nước là bao nhiêu mét?",
    options: ["1 m", "3 m", "5 m", "10 m"],
    answer: 2,
    explanation: "Theo quy định, phải để khoảng cách tối thiểu 5m so với miệng cống thoát nước khi đỗ xe để tránh cản trở thoát nước và lưu thông.",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 22,
    chapter: 1,
    content: "Hành vi nào bị cấm tuyệt đối khi lái xe ô tô?",
    options: [
      "Mở cửa sổ khi trời mát",
      "Điều khiển xe sau khi uống rượu bia dù ít",
      "Dừng xe ở trạm xăng",
      "Bật đèn chiếu xa trên đường vắng",
    ],
    answer: 1,
    explanation: "Theo Luật TTATGT 2024, người điều khiển ô tô tuyệt đối không được có nồng độ cồn trong máu hoặc hơi thở — kể cả một lượng rất nhỏ. Câu ĐIỂM LIỆT.",
    isDiemLiet: true,
    licenseClasses: ["B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 23,
    chapter: 1,
    content: "Đua xe trái phép trên đường bộ bị xử lý thế nào?",
    options: [
      "Chỉ bị phạt tiền",
      "Bị tịch thu xe và phạt tiền",
      "Bị xử lý hình sự, tịch thu phương tiện, tước GPLX vĩnh viễn",
      "Bị giữ xe 30 ngày",
    ],
    answer: 2,
    explanation: "Đua xe trái phép là tội hình sự theo BLHS 2015 (Điều 266). Người vi phạm bị truy cứu hình sự, tịch thu phương tiện và có thể tước GPLX vĩnh viễn. Câu ĐIỂM LIỆT.",
    isDiemLiet: true,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 24,
    chapter: 1,
    content: "Người điều khiển xe có được phép đi ngược chiều trên đường một chiều không?",
    options: [
      "Được nếu đường vắng",
      "Được trong tình huống khẩn cấp",
      "Không được phép trong bất kỳ trường hợp nào",
      "Được nếu đi chậm và bật đèn cảnh báo",
    ],
    answer: 2,
    explanation: "Đi ngược chiều trên đường một chiều bị nghiêm cấm tuyệt đối, kể cả trong tình huống khẩn cấp (có đường khác để đi). Câu ĐIỂM LIỆT.",
    isDiemLiet: true,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 25,
    chapter: 1,
    content: "Khi bị CSGT ra hiệu dừng xe kiểm tra, người lái phải làm gì?",
    options: [
      "Tiếp tục đi và dừng ở chỗ an toàn phía trước",
      "Tăng tốc bỏ chạy nếu chưa vi phạm gì",
      "Dừng xe ngay và chấp hành hiệu lệnh của CSGT",
      "Bấm còi và giơ tay xin đi tiếp",
    ],
    answer: 2,
    explanation: "Người tham gia giao thông phải chấp hành hiệu lệnh của CSGT, kể cả khi không có vi phạm. Không chấp hành là vi phạm pháp luật. Câu ĐIỂM LIỆT.",
    isDiemLiet: true,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 26,
    chapter: 1,
    content: "Người lái xe có nồng độ cồn trong máu từ 50 mg đến 80 mg/100 ml máu bị xử phạt thế nào?",
    options: [
      "Phạt cảnh cáo lần đầu",
      "Phạt tiền 2-3 triệu, tước GPLX 1-3 tháng",
      "Phạt tiền 6-8 triệu, tước GPLX 3-5 tháng",
      "Phạt tiền 18-20 triệu, tước GPLX 6-8 tháng",
    ],
    answer: 2,
    explanation: "Theo Nghị định 168/2024: Ô tô có nồng độ cồn mức 2 (50-<80 mg/100ml máu) phạt 6-8 triệu + tước GPLX 3-5 tháng. Câu ĐIỂM LIỆT vì liên quan nồng độ cồn.",
    isDiemLiet: true,
    licenseClasses: ["B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 27,
    chapter: 1,
    content: "Tại vạch sang đường dành cho người đi bộ, xe cơ giới phải làm gì khi có người đang qua đường?",
    options: [
      "Bấm còi để người đi bộ đi nhanh hơn",
      "Tiếp tục đi nếu đang bật đèn xanh",
      "Giảm tốc và nhường đường cho người đi bộ",
      "Chỉ nhường khi đèn đỏ",
    ],
    answer: 2,
    explanation: "Xe cơ giới phải nhường đường cho người đi bộ tại vạch sang đường (zebra crossing) kể cả khi đang có đèn xanh cho xe. Người đi bộ tại đây có quyền ưu tiên. Câu ĐIỂM LIỆT.",
    isDiemLiet: true,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 28,
    chapter: 1,
    content: "Khi xe phía sau bật đèn pha chiếu thẳng vào gương lái xe của mình ban đêm, người lái xe phía trước nên làm gì?",
    options: [
      "Phanh đột ngột để xe sau tự ý thức",
      "Điều chỉnh gương chiếu hậu và tiếp tục đi bình thường",
      "Bật đèn khẩn cấp",
      "Bóp còi liên tục",
    ],
    answer: 1,
    explanation: "Điều chỉnh góc gương hoặc nhìn sang phía khác tránh chói mắt, sau đó tiếp tục lái bình thường. Không phanh đột ngột vì gây nguy hiểm cho cả hai xe.",
    isDiemLiet: false,
    licenseClasses: ["B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 29,
    chapter: 1,
    content: "Xe ô tô được phép quay đầu tại nơi nào sau đây?",
    options: [
      "Trên cầu",
      "Đầu dốc tầm nhìn bị che khuất",
      "Đoạn đường thẳng có tầm nhìn xa, không có biển cấm quay đầu",
      "Gần vạch sang đường cho người đi bộ",
    ],
    answer: 2,
    explanation: "Chỉ được quay đầu ở nơi có tầm nhìn tốt, không có biển cấm. Không được quay đầu trên cầu, đầu dốc, gần vạch sang đường, đường hầm.",
    isDiemLiet: false,
    licenseClasses: ["B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 30,
    chapter: 1,
    content: "Khi phát hiện xe mình bị mất phanh đột ngột trên đường bằng, biện pháp xử lý đúng là:",
    options: [
      "Tắt máy xe ngay lập tức",
      "Nhấp phanh nhiều lần + về số thấp dần + phanh tay nhẹ + tìm chỗ thoát hiểm",
      "Lái xe vào lề đường và tắt máy",
      "Bơm ga mạnh để dừng xe",
    ],
    answer: 1,
    explanation: "Mất phanh: nhấp phanh để tăng áp suất, về số thấp (phanh động cơ), phanh tay từng đợt nhẹ. Không tắt máy đột ngột (mất lái trợ lực). Câu ĐIỂM LIỆT.",
    isDiemLiet: true,
    licenseClasses: ["B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 31,
    chapter: 1,
    content: "Khi lái xe trên đường cao tốc, khoảng cách an toàn tối thiểu với xe phía trước là bao nhiêu mét (ở tốc độ 100 km/h)?",
    options: ["50 m", "70 m", "100 m", "Theo biển chỉ dẫn trên đường"],
    answer: 3,
    explanation: "Trên đường cao tốc, khoảng cách an toàn được quy định bằng biển báo riêng từng đoạn. Tuy nhiên tối thiểu phải đảm bảo đủ tầm nhìn dừng xe — thông thường 100m ở tốc độ 100km/h.",
    isDiemLiet: false,
    licenseClasses: ["B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 32,
    chapter: 1,
    content: "Người ngồi trên xe ô tô có bắt buộc thắt dây an toàn không?",
    options: [
      "Chỉ người ngồi ghế trước",
      "Bắt buộc tất cả người ngồi trên xe (trừ trẻ em dùng ghế riêng)",
      "Không bắt buộc nếu đi đường ngắn",
      "Chỉ bắt buộc trên đường cao tốc",
    ],
    answer: 1,
    explanation: "Tất cả người ngồi trên ô tô đều phải thắt dây an toàn. Câu ĐIỂM LIỆT — không thắt dây an toàn (với lái xe) là vi phạm nghiêm trọng.",
    isDiemLiet: true,
    licenseClasses: ["B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 33,
    chapter: 1,
    content: "Xe ô tô được phép đỗ cách bao nhiêu mét so với đèn tín hiệu giao thông?",
    options: ["5 m", "10 m", "15 m", "20 m"],
    answer: 1,
    explanation: "Theo quy định, không được đỗ xe trong phạm vi 10m tính từ đèn tín hiệu giao thông.",
    isDiemLiet: false,
    licenseClasses: ["B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 34,
    chapter: 1,
    content: "Người lái xe sử dụng ma túy hoặc chất kích thích bị cấm điều khiển xe theo quy định nào?",
    options: [
      "Chỉ bị cấm nếu có triệu chứng say",
      "Bị cấm tuyệt đối — kể cả liều thấp theo toa thuốc gây buồn ngủ",
      "Chỉ cấm ma túy, không cấm thuốc an thần",
      "Chỉ bị nhắc nhở lần đầu",
    ],
    answer: 1,
    explanation: "Cấm tuyệt đối điều khiển xe khi dùng ma túy, chất kích thích hoặc thuốc gây buồn ngủ/ảnh hưởng hành vi. Câu ĐIỂM LIỆT.",
    isDiemLiet: true,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 35,
    chapter: 1,
    content: "Hành vi nào sau đây vi phạm quy tắc nhường đường?",
    options: [
      "Nhường đường cho xe cứu thương khi đang bật đèn xanh",
      "Không nhường đường cho xe lăn (người khuyết tật) tại ngã tư",
      "Nhường đường cho người đi bộ tại vạch kẻ",
      "Dừng xe cho xe cứu hỏa qua",
    ],
    answer: 1,
    explanation: "Không nhường đường cho xe ưu tiên (kể cả xe của người khuyết tật trong một số trường hợp) là vi phạm. Câu ĐIỂM LIỆT.",
    isDiemLiet: true,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },

  // ===== CHƯƠNG I — thêm câu thông thường =====
  {
    id: 36,
    chapter: 1,
    content: "Xe ô tô con được phép chạy tốc độ tối đa bao nhiêu km/h trên đường ngoài khu dân cư (đường đôi có dải phân cách)?",
    options: ["60 km/h", "70 km/h", "80 km/h", "90 km/h"],
    answer: 3,
    explanation: "Trên đường ngoài khu dân cư có dải phân cách, ô tô con được phép chạy tối đa 90 km/h.",
    isDiemLiet: false,
    licenseClasses: ["B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 37,
    chapter: 1,
    content: "Người điều khiển mô tô phải đội mũ bảo hiểm đạt chuẩn. Hành khách ngồi sau có bắt buộc không?",
    options: ["Không bắt buộc nếu ngồi phía sau", "Bắt buộc — cả người lái và hành khách đều phải đội", "Chỉ bắt buộc trên đường cao tốc", "Chỉ bắt buộc với trẻ em"],
    answer: 1,
    explanation: "Tất cả người ngồi trên xe mô tô, gắn máy đều phải đội mũ bảo hiểm đạt chuẩn (cả lái xe lẫn hành khách).",
    isDiemLiet: false,
    licenseClasses: ["A1", "A"],
  },
  {
    id: 38,
    chapter: 1,
    content: "Khi trời mưa to, tầm nhìn kém, người lái xe phải làm gì?",
    options: [
      "Tắt đèn để tiết kiệm pin",
      "Giảm tốc, bật đèn sương mù hoặc đèn chiếu gần",
      "Tăng tốc để qua nhanh vùng mưa",
      "Dừng giữa đường chờ tạnh mưa",
    ],
    answer: 1,
    explanation: "Khi tầm nhìn kém do mưa: bật đèn sương mù hoặc đèn chiếu gần, giảm tốc độ, tăng khoảng cách an toàn. Không tắt đèn.",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 39,
    chapter: 1,
    content: "Xe ô tô có được phép vừa lái vừa nghe điện thoại qua tai nghe không?",
    options: [
      "Được phép nếu dùng tai nghe một bên",
      "Được phép nếu tốc độ thấp",
      "Không được phép — phải dùng thiết bị rảnh tay (handsfree) gắn cố định",
      "Được phép trong đô thị",
    ],
    answer: 2,
    explanation: "Chỉ được phép nghe điện thoại qua thiết bị hỗ trợ rảnh tay (handsfree) gắn cố định trên xe. Không được cầm điện thoại hoặc đeo tai nghe khi lái.",
    isDiemLiet: false,
    licenseClasses: ["B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 40,
    chapter: 1,
    content: "Trên đường cao tốc, khi xe bị hỏng, người lái phải làm gì ngay lập tức?",
    options: [
      "Sửa xe tại chỗ trên làn cao tốc",
      "Đưa xe vào làn khẩn cấp, đặt tam giác cảnh báo và gọi cứu hộ",
      "Đứng trên làn đường vẫy xe khác",
      "Tắt máy và chờ",
    ],
    answer: 1,
    explanation: "Xe hỏng trên cao tốc: đưa ngay vào làn khẩn cấp (lề đường), đặt tam giác cảnh báo phía sau ≥150m, bật đèn khẩn cấp và gọi cứu hộ. Không được đứng trên làn chạy.",
    isDiemLiet: false,
    licenseClasses: ["B1", "B", "C1", "C", "D1", "D2", "D"],
  },

  // ===== CHƯƠNG II — bổ sung =====
  {
    id: 182,
    chapter: 2,
    content: "Hành vi nào thể hiện văn hóa giao thông kém?",
    options: [
      "Bật xi nhan trước khi rẽ",
      "Nhường đường tại vạch sang đường",
      "Dừng đỗ xe trên vỉa hè chắn lối đi bộ",
      "Giảm tốc khi qua khu dân cư",
    ],
    answer: 2,
    explanation: "Đỗ xe trên vỉa hè cản trở người đi bộ là hành vi thiếu văn hóa giao thông và vi phạm pháp luật.",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 183,
    chapter: 2,
    content: "Khi mang xe đi sửa, bình xăng còn dư, chủ xe có cần lưu ý gì về phòng cháy chữa cháy?",
    options: [
      "Không cần lưu ý gì",
      "Đổ xăng thêm đầy bình để tiện",
      "Giảm lượng xăng trong bình và thông báo thợ sửa chữa về nguy cơ cháy nổ",
      "Chỉ cần tắt máy",
    ],
    answer: 2,
    explanation: "Xăng là chất dễ cháy. Khi sửa chữa, cần giảm xăng, tránh tia lửa và thông báo thợ về rủi ro cháy nổ, đặc biệt khi hàn xì.",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 184,
    chapter: 2,
    content: "Người lái xe có trách nhiệm đạo đức nào khi chứng kiến vụ tai nạn giao thông?",
    options: [
      "Tiếp tục đi để không làm tắc đường",
      "Dừng lại, gọi 113/115, sơ cứu nếu có thể, bảo vệ hiện trường",
      "Chụp ảnh đăng mạng xã hội",
      "Chờ cảnh sát đến rồi khai chứng",
    ],
    answer: 1,
    explanation: "Trách nhiệm pháp lý và đạo đức: dừng xe, gọi cứu thương (115) và cảnh sát (113), sơ cứu nạn nhân, bảo vệ hiện trường. Bỏ mặc nạn nhân có thể bị xử lý hình sự.",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },

  // ===== CHƯƠNG III — bổ sung =====
  {
    id: 207,
    chapter: 3,
    content: "Khi lái xe lên dốc gặp xe ngược chiều, xe nào phải nhường đường?",
    options: [
      "Xe to hơn nhường xe nhỏ hơn",
      "Xe đi xuống nhường xe đi lên vì xe lên khó dừng lại",
      "Xe nào ở gần lề đường hơn thì nhường",
      "Xe nào đến trước thì đi trước",
    ],
    answer: 1,
    explanation: "Xe đi xuống dốc phải nhường xe đi lên vì xe đang lên có quán tính, khó dừng giữa chừng và nguy hiểm hơn.",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 208,
    chapter: 3,
    content: "Kỹ thuật lái xe an toàn khi vào cua là:",
    options: [
      "Tăng tốc để qua nhanh",
      "Giảm tốc trước khi vào cua, không phanh khi đang trong cua",
      "Phanh mạnh trong cua để an toàn",
      "Chỉ giảm tốc khi đường trơn",
    ],
    answer: 1,
    explanation: "Quy tắc vào cua: 'Giảm tốc trước cua — Đạp ga trong cua'. Phanh khi đang trong cua rất nguy hiểm vì dễ bị văng ra ngoài.",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 209,
    chapter: 3,
    content: "Khi lái xe vào ban đêm, khi gặp xe ngược chiều phải làm gì với đèn pha?",
    options: [
      "Bật thêm đèn pha cho sáng hơn",
      "Chuyển từ đèn pha (chiếu xa) sang đèn cos (chiếu gần) khi cách 150-200m",
      "Tắt đèn để không làm chói mắt xe ngược chiều",
      "Giữ nguyên đèn pha",
    ],
    answer: 1,
    explanation: "Phải chuyển đèn pha (far/high beam) sang đèn cos (low beam/chiếu gần) khi gặp xe ngược chiều cách 150-200m để tránh chói mắt người lái xe ngược chiều.",
    isDiemLiet: false,
    licenseClasses: ["B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 215,
    chapter: 3,
    content: "Khi xe bị trơn trượt ngang (xe bị quay đuôi), người lái cần làm gì?",
    options: [
      "Đạp phanh mạnh để dừng xe ngay",
      "Đánh lái ngược chiều trượt và thả ga từ từ",
      "Tăng ga để thoát trượt",
      "Đánh lái cùng chiều trượt",
    ],
    answer: 1,
    explanation: "Xe bị trượt ngang (oversteer): đánh lái về phía đuôi xe đang trượt sang (counter-steer) và nhả ga từ từ để lấy lại kiểm soát. Câu ĐIỂM LIỆT.",
    isDiemLiet: true,
    licenseClasses: ["B1", "B", "C1", "C", "D1", "D2", "D"],
  },

  // ===== CHƯƠNG IV — bổ sung =====
  {
    id: 265,
    chapter: 4,
    content: "Đèn báo áp suất dầu (hình giọt dầu) sáng đỏ khi đang chạy xe, người lái cần:",
    options: [
      "Tiếp tục đi, đèn tắt sau vài phút",
      "Dừng xe ngay, tắt máy và kiểm tra mức dầu — không tiếp tục chạy",
      "Đổ thêm nước làm mát",
      "Chạy thêm vài km rồi kiểm tra",
    ],
    answer: 1,
    explanation: "Đèn dầu sáng = áp suất dầu thấp = động cơ có thể bị hỏng nghiêm trọng trong vài giây. Phải dừng ngay và tắt máy.",
    isDiemLiet: false,
    licenseClasses: ["B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 266,
    chapter: 4,
    content: "Hệ thống phanh ABS có tác dụng gì khi xe phanh gấp?",
    options: [
      "Dừng xe nhanh hơn phanh thường",
      "Ngăn bánh bị bó cứng, giữ khả năng lái trong khi phanh",
      "Tăng lực phanh gấp đôi",
      "Khóa tất cả bánh để dừng xe nhanh nhất",
    ],
    answer: 1,
    explanation: "ABS (Anti-lock Braking System) tự động nhả và bóp phanh liên tục để ngăn bánh bị bó, giúp tài xế vẫn điều khiển lái được trong khi đang phanh mạnh.",
    isDiemLiet: false,
    licenseClasses: ["B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 267,
    chapter: 4,
    content: "Khi lốp xe bị mòn đến mức nào cần thay lốp mới?",
    options: [
      "Khi lốp có vết nứt nhỏ",
      "Khi độ sâu gai lốp còn dưới 1,6mm (hoặc chỉ báo mòn lốp ngang bằng mặt gai)",
      "Khi lốp đã dùng được 5 năm",
      "Khi áp suất lốp thường xuyên giảm",
    ],
    answer: 1,
    explanation: "Lốp cần thay khi chiều sâu gai còn <1,6mm. Nhiều lốp có chỉ báo mòn (wear indicator) — khi mặt gai ngang bằng chỉ báo này là phải thay.",
    isDiemLiet: false,
    licenseClasses: ["B1", "B", "C1", "C", "D1", "D2", "D"],
  },

  // ===== CHƯƠNG V — bổ sung biển báo =====
  {
    id: 302,
    chapter: 5,
    content: "Biển báo hình tròn viền đỏ có số '50' bên trong có nghĩa là gì?",
    options: [
      "Tốc độ tối thiểu 50 km/h",
      "Giới hạn tốc độ tối đa 50 km/h",
      "Cách điểm đến 50 km",
      "Trọng lượng tối đa 50 tấn",
    ],
    answer: 1,
    explanation: "Biển tròn viền đỏ có số là biển CẤM — cấm chạy quá tốc độ ghi trên biển. Số '50' = tốc độ tối đa 50 km/h.",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 303,
    chapter: 5,
    content: "Biển báo hình tam giác có hình người đi bộ bên trong có ý nghĩa gì?",
    options: [
      "Khu vực dành riêng cho người đi bộ",
      "Cảnh báo có người đi bộ qua đường phía trước",
      "Cấm người đi bộ",
      "Vạch sang đường phía trước",
    ],
    answer: 1,
    explanation: "Biển tam giác cảnh báo: 'Chú ý — có người đi bộ qua đường phía trước'. Người lái phải giảm tốc và quan sát.",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 304,
    chapter: 5,
    content: "Biển 'STOP' (hình bát giác đỏ) yêu cầu người lái xe phải làm gì?",
    options: [
      "Giảm tốc và đi tiếp nếu đường thông",
      "Dừng hẳn trước vạch, quan sát kỹ rồi mới đi",
      "Nhường đường cho xe ưu tiên",
      "Dừng 5 giây rồi đi",
    ],
    answer: 1,
    explanation: "Biển STOP bắt buộc phải dừng hẳn (không chỉ giảm tốc) trước vạch dừng, quan sát an toàn hai chiều trước khi đi tiếp.",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 305,
    chapter: 5,
    content: "Vạch kẻ đường màu vàng liên tục ở giữa đường có nghĩa là gì?",
    options: [
      "Cho phép vượt khi an toàn",
      "Cấm vượt và cấm sang làn ngược chiều",
      "Phân chia làn xe trong cùng chiều",
      "Chỉ cấm vượt ban đêm",
    ],
    answer: 1,
    explanation: "Vạch vàng liên tục ở giữa đường: cấm tuyệt đối vượt xe và cấm sang làn ngược chiều. Nghiêm trọng hơn vạch trắng liên tục.",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 306,
    chapter: 5,
    content: "Biển báo hình vuông nền xanh lam có mũi tên thẳng và mũi tên sang phải nghĩa là gì?",
    options: [
      "Được rẽ phải hoặc đi thẳng",
      "Bắt buộc phải rẽ phải",
      "Cấm rẽ trái",
      "Ưu tiên đường thẳng",
    ],
    answer: 0,
    explanation: "Biển hiệu lệnh (nền xanh lam) có hai mũi tên: đi thẳng và rẽ phải — tức là được chọn một trong hai hướng đó.",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 307,
    chapter: 5,
    content: "Biển cấm ô tô (hình tròn viền đỏ có hình xe hơi bên trong) có áp dụng cho xe máy không?",
    options: [
      "Có — cấm tất cả xe cơ giới",
      "Không — chỉ cấm xe ô tô, xe máy vẫn được đi",
      "Có — nếu xe máy phân khối lớn",
      "Tùy theo quy định địa phương",
    ],
    answer: 1,
    explanation: "Biển cấm ô tô chỉ áp dụng cho xe ô tô. Xe máy, xe đạp không thuộc phạm vi cấm này (trừ khi có biển phụ ghi rõ thêm).",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 308,
    chapter: 5,
    content: "Biển báo 'Đường ưu tiên' (hình thoi màu vàng viền trắng) có nghĩa gì?",
    options: [
      "Đường này chỉ dành cho xe ưu tiên (cảnh sát, cứu thương)",
      "Xe trên đường này được ưu tiên so với xe từ đường khác đâm ra",
      "Cấm dừng đỗ xe trên đường này",
      "Tốc độ tối thiểu trên đường này",
    ],
    answer: 1,
    explanation: "Biển 'Đường ưu tiên' báo hiệu xe đang đi trên đường được ưu tiên qua ngã tư. Xe từ các đường phụ khác phải nhường.",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 309,
    chapter: 5,
    content: "Biển số R.301 'Cấm đi ngược chiều' (vạch đỏ ngang trên nền trắng) đặt ở đâu?",
    options: [
      "Cuối đường một chiều",
      "Đầu đường cấm xe vào (người lái xe nhìn thấy nghĩa là đang đi sai chiều)",
      "Tại ngã tư",
      "Trước cầu hẹp",
    ],
    answer: 1,
    explanation: "Biển 'Cấm đi ngược chiều' đặt ở đầu đường một chiều (đầu hướng ngược). Nếu bạn nhìn thấy biển này, nghĩa là bạn đang đi ngược chiều và phải dừng lại.",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 310,
    chapter: 5,
    content: "Biển báo tam giác có hình đường ray xe lửa nghĩa là:",
    options: [
      "Ga tàu phía trước",
      "Cảnh báo sắp đến đường sắt giao cắt — cần chú ý và giảm tốc",
      "Cấm xe qua đường sắt",
      "Đường sắt đang sửa chữa",
    ],
    answer: 1,
    explanation: "Biển tam giác đường sắt cảnh báo sắp đến điểm giao cắt với đường sắt. Người lái phải giảm tốc, quan sát cả hai phía và tuân thủ tín hiệu tại đường sắt.",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },

  // ===== CHƯƠNG VI — bổ sung tình huống =====
  {
    id: 487,
    chapter: 6,
    content: "Xe A đang đi thẳng trên đường ưu tiên. Xe B từ đường phụ bên trái muốn vào đường ưu tiên. Ai ưu tiên?",
    options: [
      "Xe B vì đến từ bên trái (quy tắc ưu tiên bên phải không áp dụng)",
      "Xe A — đang đi trên đường ưu tiên nên được ưu tiên tuyệt đối",
      "Xe nào đến trước thì đi trước",
      "Xe A nhường xe B vì xe B đứng chờ lâu hơn",
    ],
    answer: 1,
    explanation: "Xe trên đường ưu tiên (có biển thoi vàng) luôn được ưu tiên. Xe từ đường phụ phải chờ và nhường.",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 488,
    chapter: 6,
    content: "Tại ngã tư đèn xanh, xe A đang rẽ trái, xe B đang đi thẳng ngược chiều. Ai nhường ai?",
    options: [
      "Xe A rẽ trái nhường xe B đi thẳng",
      "Xe B nhường xe A vì xe A rẽ trái khó hơn",
      "Xe nào đến ngã tư trước thì đi trước",
      "Xe A được ưu tiên vì đang rẽ",
    ],
    answer: 0,
    explanation: "Xe rẽ trái LUÔN phải nhường xe đi thẳng ngược chiều. Đây là quy tắc cơ bản nhất tại ngã tư.",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 489,
    chapter: 6,
    content: "Trong sa hình: 3 xe A, B, C cùng đến ngã tư không đèn, không biển. A đến từ phía Bắc đi thẳng, B từ phía Tây rẽ phải, C từ phía Đông rẽ trái. Thứ tự ưu tiên là:",
    options: [
      "A → B → C",
      "B → A → C",
      "C → B → A",
      "B → C → A",
    ],
    answer: 1,
    explanation: "Áp dụng quy tắc ưu tiên bên phải: B (từ Tây) có xe A (từ Bắc) ở bên phải nên A nhường B. A có C ở bên phải nên C nhường A. Thứ tự: B trước → A → C.",
    isDiemLiet: false,
    licenseClasses: ["B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 490,
    chapter: 6,
    content: "Xe bạn đang đi thẳng, xe ngược chiều muốn rẽ trái cắt qua đầu xe bạn. Bạn nên:",
    options: [
      "Nhường đường cho xe ngược chiều vì họ khó rẽ hơn",
      "Giữ nguyên tốc độ và đường đi — xe ngược chiều phải nhường bạn",
      "Phanh gấp và nhường",
      "Bấm còi và vượt lên trước",
    ],
    answer: 1,
    explanation: "Xe rẽ trái phải nhường xe đi thẳng ngược chiều. Bạn có quyền ưu tiên, không cần nhường — nhưng cần đề phòng xe rẽ cắt đường.",
    isDiemLiet: false,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 491,
    chapter: 6,
    content: "Xe bạn bị mất phanh khi đang xuống dốc dài, trước mặt là vực. Phương án nào tốt nhất?",
    options: [
      "Nhảy ra khỏi xe ngay",
      "Tắt máy xe và để xe tự dừng",
      "Tìm chướng ngại vật mềm (bụi cây, đống cát) hoặc lề núi để đâm vào giảm tốc, dùng phanh tay",
      "Lái thẳng xuống dốc và cầu nguyện",
    ],
    answer: 2,
    explanation: "Mất phanh: ưu tiên dùng phanh tay từng đợt, về số thấp nhất, tìm vật cản mềm để giảm tốc an toàn. Không nhảy ra vì tốc độ cao rất nguy hiểm. Câu ĐIỂM LIỆT.",
    isDiemLiet: true,
    licenseClasses: ["B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 252,
    chapter: 3,
    content: "Khi xe bị thủng lốp (nổ lốp) ở bánh trước đang chạy tốc độ cao, cảm giác của người lái là:",
    options: [
      "Xe bỗng nhẹ hẳn và dễ lái hơn",
      "Vô lăng giật mạnh về phía lốp bị thủng, xe khó giữ thẳng",
      "Xe tự dừng lại",
      "Không cảm nhận được gì",
    ],
    answer: 1,
    explanation: "Nổ lốp trước: vô lăng giật mạnh về phía lốp thủng. Phải giữ chặt vô lăng, không phanh gấp, thả ga từ từ và lái về lề an toàn. Câu ĐIỂM LIỆT.",
    isDiemLiet: true,
    licenseClasses: ["B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 253,
    chapter: 3,
    content: "Kỹ thuật lái xe an toàn khi vượt xe khác trên đường hai chiều:",
    options: [
      "Vượt khi thấy đường thẳng dù không thấy xa",
      "Quan sát kỹ phía trước (ít nhất 300m), bật xi nhan trái, tăng tốc vượt nhanh và về làn phải sau khi vượt",
      "Bấm còi liên tục khi vượt",
      "Vượt bên phải để an toàn hơn",
    ],
    answer: 1,
    explanation: "Vượt xe đúng kỹ thuật: quan sát xa, bật xi nhan, tăng tốc đủ để vượt nhanh, về làn phải ngay sau khi vượt. Câu ĐIỂM LIỆT nếu vượt sai quy định.",
    isDiemLiet: true,
    licenseClasses: ["B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 254,
    chapter: 3,
    content: "Khi lái xe ô tô qua vũng nước sâu chưa rõ độ sâu, cách xử lý đúng là:",
    options: [
      "Lao nhanh qua để ít bị ướt",
      "Đi chậm, số thấp, giữ ga đều tay — không phanh giữa chừng trong nước",
      "Dừng lại và chờ nước rút",
      "Đi số cao để không bị ngập động cơ",
    ],
    answer: 1,
    explanation: "Qua vũng nước: đi chậm, số thấp, giữ ga đều để nước không bị hút vào ống xả. Không phanh đột ngột (dễ bị trơn). Câu ĐIỂM LIỆT.",
    isDiemLiet: true,
    licenseClasses: ["B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 255,
    chapter: 3,
    content: "Sau khi lái xe qua vũng nước, phanh có thể bị ướt và giảm hiệu quả. Cách xử lý:",
    options: [
      "Không cần làm gì, phanh tự khô",
      "Dừng xe ngay",
      "Nhấp phanh nhẹ nhiều lần trong khi đang đi để phanh khô nhanh bằng ma sát",
      "Tăng tốc để sấy khô phanh",
    ],
    answer: 2,
    explanation: "Nhấp phanh nhẹ liên tục tạo ma sát giúp phanh khô nhanh hơn. Không dừng đột ngột vì phanh đang yếu. Câu ĐIỂM LIỆT.",
    isDiemLiet: true,
    licenseClasses: ["B1", "B", "C1", "C", "D1", "D2", "D"],
  },
  {
    id: 260,
    chapter: 3,
    content: "Khi phát hiện đột ngột có người đi bộ bước ra đường trước mũi xe, cách xử lý nào đúng nhất?",
    options: [
      "Bấm còi mạnh và tăng tốc",
      "Phanh gấp + bẻ lái tránh sang bên nếu đủ không gian",
      "Nhắm mắt và phanh hết lực",
      "Rú ga qua nhanh",
    ],
    answer: 1,
    explanation: "Ưu tiên phanh gấp. Nếu không kịp dừng, có thể lái tránh sang lề/bên nếu đường thông thoáng. Câu ĐIỂM LIỆT — phải biết xử lý tình huống nguy cấp.",
    isDiemLiet: true,
    licenseClasses: ["A1", "A", "B1", "B", "C1", "C", "D1", "D2", "D"],
  },
];

// Helper: get questions for a license class
export function getQuestionsForClass(questions: Question[], licenseClass: string): Question[] {
  return questions.filter((q) => q.licenseClasses.includes(licenseClass as any));
}

// Verify điểm liệt flagging matches official list
export function validateDiemLiet(questions: Question[]): { correct: number; wrong: number[] } {
  const wrong: number[] = [];
  for (const q of questions) {
    const shouldBeDiemLiet = DIEM_LIET_IDS.has(q.id);
    if (shouldBeDiemLiet !== q.isDiemLiet) wrong.push(q.id);
  }
  return { correct: questions.length - wrong.length, wrong };
}
